# Generated by Django 5.0.1 on 2024-01-12 02:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieAtePerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_calorie', models.PositiveIntegerField(editable=False)),
                ('current_calorie', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('create_data', models.DateField(auto_now_add=True)),
                ('destroy_data', models.DateField(default=datetime.date(2024, 1, 13), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=255)),
                ('calories', models.PositiveIntegerField()),
                ('time_of_add', models.DateTimeField(auto_now_add=True)),
                ('calorie_today', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='calorie_tracker.calorieateperday')),
            ],
        ),
        migrations.CreateModel(
            name='UserCalorieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(None, 'Gender'), (1, 'male'), (2, 'female')])),
                ('age', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calorie_per_day', models.PositiveIntegerField(editable=False)),
                ('physical_activity', models.IntegerField(choices=[(None, 'Physical Activity'), (0, 'without'), (1, 'light'), (2, 'middle'), (3, 'high'), (4, 'very high')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calorie_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calorieateperday',
            name='calorie_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calorie_history', to='calorie_tracker.usercaloriedata'),
        ),
    ]
