# Generated by Django 5.0.1 on 2024-01-09 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Userprofile', 'verbose_name_plural': 'Userprofile'},
        ),
    ]
